name: OrangeFox - Build

# Credits to:
# https://github.com/TeamWin
# https://gitlab.com/OrangeFox
# https://github.com/azwhikaru for Recovery Builder Template
# And all Contributors in every repositories I used

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'OFOX Branch \ Version'
        required: true
        default: '9.0'
        type: choice
        options:
        - 12.1
        - 11.0
        - 10.0
        - 9.0
        - 8.1
        - 8.0
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/DZZN-DEV/twrp_device_tree_doogee_s40.git'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'android-9.0'
      DEVICE_PATH:
        description: 'Specify your device path.'
        required: true
        default: 'device/doogee/S40'
      DEVICE_NAME:
        description: 'Specify your Device Codename.'
        required: true
        default: 'S40'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendorboot

jobs:
  build:
    name: Build OFRP by ${{ github.actor }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
              
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Build Environment
      run: |
        sudo apt install aria2 -y
        git clone https://gitlab.com/OrangeFox/misc/scripts
        cd scripts
        sudo bash setup/android_build_env.sh

    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
      
    - name: Set-up Manifest
      if: github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1'
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git config --global user.name "DZZN-DEV"
        git config --global user.email "davenplay@gmail.com"
        git clone https://github.com/DZZN-DEV/sync.git
        cd sync
        chmod +x orangefox_sync.sh
        ./orangefox_sync.sh --branch ${{ github.event.inputs.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}

    - name: Clone Device Tree
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        git clone ${{ github.event.inputs.DEVICE_TREE }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
        cd ${{ github.event.inputs.DEVICE_PATH }}
        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Check Manifest Branch
      uses: haya14busa/action-cond@v1
      id: fox_branch
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == '11.0' || github.event.inputs.MANIFEST_BRANCH == '12.1' }}
        if_true: lunch twrp_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka adbd ${{ github.event.inputs.BUILD_TARGET }}image
        if_false: lunch omni_${{ github.event.inputs.DEVICE_NAME }}-eng && make clean && mka ${{ github.event.inputs.BUILD_TARGET }}image

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Switch to Python2
      run: |
        sudo apt -y install python
        sudo rm -rf /usr/bin/python
        sudo ln -s /usr/bin/python2 /usr/bin/python
        # sudo ln -s /usr/bin/python3 /usr/bin/python3
      continue-on-error: true
      
    - name: Building OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        set +e
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export TARGET_ARCH=arm64
        export BUILD_2GB_VERSION=1
        export FOX_REPLACE_BUSYBOX_PS=1
        export FOX_USE_BASH_SHELL=1
        export FOX_USE_LZMA_COMPRESSION=1
        export FOX_USE_NANO_EDITOR=1
        export OF_USE_MAGISKBOOT=1
        export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
        export OF_TWRP_COMPATIBILITY_MODE=1
        export OF_DISABLE_MIUI_SPECIFIC_FEATURES=1
        export OF_FORCE_DISABLE_DM_VERITY_FORCED_ENCRYPTION=1
        export OF_DISABLE_DM_VERITY_FORCED_ENCRYPTION=1
        export OF_NO_MIUI_OTA_VENDOR_BACKUP=1
        export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
        export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
        export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
        export OF_USE_NEW_MAGISKBOOT=1
        export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
        export FOX_DELETE_AROMAFM=1
        export OF_USE_GREEN_LED=0
        export OF_FLASHLIGHT_ENABLE=1
        export TW_DEFAULT_LANGUAGE=en
        export FOX_BUILD_TYPE=UNOFFICIAL
        export FOX_VERSION=9.0
        export USE_CCACHE=1
        export OF_MAINTAINER=DZZN-DEV
        export OF_HIDE_NOTCH=1
        export OF_CLOCK_POS=1
        export OF_ALLOW_DISABLE_NAVBAR=1
        export OF_DONT_KEEP_LOG_HISTORY=1
        export OF_NO_MIUI_PATCH_WARNING=1
        export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1
        export FOX_USE_XZ_UTILS=1
        export FOX_LEGACY_TOOLS=1
        export FOX_USE_LZMA_COMPRESSION=1
        export LZMA_RAMDISK_TARGETS=recovery
        export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
        export OF_USE_MAGISKBOOT=1
        set -e
        ${{ steps.fox_branch.outputs.value }}

    - name: Set Build Date # For Build Date Info, currently using Asia/Manila
      run: |
        echo "BUILD_DATE=$(TZ=Europe/Berlin date+%d%m%Y)" >> $GITHUB_ENV

    - name: Check if Recovery Exist
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img ]; then
            echo "CHECK_IMG_IS_OK=true" >> $GITHUB_ENV
            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi
        if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip ]; then
            echo "CHECK_ZIP_IS_OK=true" >> $GITHUB_ENV
            echo "MD5_ZIP=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip | cut -d ' ' -f 1)" >> $GITHUB_ENV
        else
            echo "Recovery out directory is empty."
        fi

    - name: Upload to Release
      if: env.CHECK_IMG_IS_OK == 'true' && env.CHECK_ZIP_IS_OK == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.img
          OrangeFox/fox_${{ github.event.inputs.MANIFEST_BRANCH }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/OrangeFox*.zip
        name: Unofficial OrangeFox for ${{ github.event.inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ github.event.inputs.DEVICE_TREE }}/tree/${{ github.event.inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ github.event.inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
          MD5 (img): ${{ env.MD5_IMG }}
          MD5 (zip): ${{ env.MD5_ZIP }}
